name: my_quran
description: A minimal app to read the Quran.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+3

environment:
  sdk: ^3.10.0
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/fonts/
      - assets/quran.json
      - assets/search_index.json

  fonts:
    - family: Scheherazade
      fonts: 
        - asset: assets/fonts/ScheherazadeNew-Medium.ttf
    - family: Rustam
      fonts: 
        - asset: assets/fonts/rustam_quranR3HOQ.ttf